[{"text": ["Python IDLE subprocess error?"], "childNum": 0, "tag": "h2", "senID": 0, "childList": []}, {"text": ["Don't think this has been asked-how come this comes up occasionally when running very simple programs-I then have to go to Task Manager &amp; stop all Pythonw processes to get it to work again?"], "childNum": 0, "tag": "p", "senID": 1, "childList": []}, {"text": ["It seems to happen randomnly on different bits of code-here is the one I'm doing at the moment-"], "childNum": 0, "tag": "p", "senID": 2, "childList": []}, {"code": "<pre>\n<code>\n f = open('money.txt')\ncurrentmoney = float(f.readline())\nprint(currentmoney, end='')\nhowmuch = (float(input('How much did you put in or take out?:')))\nnow = currentmoney + howmuch\nprint(now)\nf.close()\nf = open('money.txt', 'w')\nf.write(str(now))\nf.close()\n</code>\n</pre>\n", "senID": 3}, {"text": ["Sometimes it works, sometimes it doesn't!"], "childNum": 0, "tag": "p", "senID": 4, "childList": []}]