<h3>Question (ID-2952187):</h3><h2>Getting "Error loading MySQLdb module: No module named MySQLdb" - have tried previously posted solutions</h2><p>This is a much discussed issue for OSX 10.6 users, but I haven't been able to find a solution that works. Here's my setup:</p>

<p>Python 2.6.1 64bit
Django 1.2.1
MySQL 5.1.47 osx10.6 64bit</p>

<p>I create a virtualenvwrapper with --no-site-packages, then installed Django. When I activate the virtualenv and run python manage.py syncdb, I get this error:</p>

<pre><code>Traceback (most recent call last):
File "manage.py", line 11, in &lt;module&gt;
  execute_manager(settings)
File "/Users/joerobinson/.virtualenvs/dj_tut/lib/python2.6/site-packages/django/core/management/__init__.py", line 438, in execute_manager
  utility.execute()
File "/Users/joerobinson/.virtualenvs/dj_tut/lib/python2.6/site-packages/django/core/management/__init__.py", line 379, in execute
  self.fetch_command(subcommand).run_from_argv(self.argv)
File "/Users/joerobinson/.virtualenvs/dj_tut/lib/python2.6/site-packages/django/core/management/__init__.py", line 257, in fetch_command
  klass = load_command_class(app_name, subcommand)
File "/Users/joerobinson/.virtualenvs/dj_tut/lib/python2.6/site-packages/django/core/management/__init__.py", line 67, in load_command_class
  module = import_module('%s.management.commands.%s' % (app_name, name))
File "/Users/joerobinson/.virtualenvs/dj_tut/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
  __import__(name)
File "/Users/joerobinson/.virtualenvs/dj_tut/lib/python2.6/site-packages/django/core/management/commands/syncdb.py", line 7, in &lt;module&gt;
from django.core.management.sql import custom_sql_for_model, emit_post_sync_signal
File "/Users/joerobinson/.virtualenvs/dj_tut/lib/python2.6/site-packages/django/core/management/sql.py", line 5, in &lt;module&gt;
from django.contrib.contenttypes import generic
File "/Users/joerobinson/.virtualenvs/dj_tut/lib/python2.6/site-packages/django/contrib/contenttypes/generic.py", line 6, in &lt;module&gt;
  from django.db import connection
File "/Users/joerobinson/.virtualenvs/dj_tut/lib/python2.6/site-packages/django/db/__init__.py", line 75, in &lt;module&gt;
  connection = connections[DEFAULT_DB_ALIAS]
File "/Users/joerobinson/.virtualenvs/dj_tut/lib/python2.6/site-packages/django/db/utils.py", line 91, in __getitem__
  backend = load_backend(db['ENGINE'])
File "/Users/joerobinson/.virtualenvs/dj_tut/lib/python2.6/site-packages/django/db/utils.py", line 32, in load_backend
  return import_module('.base', backend_name)
File "/Users/joerobinson/.virtualenvs/dj_tut/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
  __import__(name)
File "/Users/joerobinson/.virtualenvs/dj_tut/lib/python2.6/site-packages/django/db/backends/mysql/base.py", line 14, in &lt;module&gt;
  raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: No module named MySQLdb
</code></pre>

<p>I've also installed the <a href="http://sourceforge.net/projects/mysql-python/files/" rel="nofollow">MySQL for Python</a> adapter, but to no avail (maybe I installed it improperly?). </p>

<p>Anyone dealt with this before?</p>
<br /><h3>Answers (Total-6):</h3><b>#0</b><br /><p>I had the same error and easy_install / pip install MySQL-python fixed it.</p>
<br /><b>#1</b><br /><p>running ubuntu, had to do sudo apt-get install python-mysqldb</p>
<br /><b>#2</b><br /><p>This issue was the result of an incomplete / incorrect installation of the MySQL for Python adapter. Specifically, I had to edit the path to the mysql_config file to point to /usr/local/mysql/bin/mysql_config - discussed in greater detail in this article: <a href="http://dakrauth.com/blog/entry/python-and-django-setup-mac-os-x-leopard/" rel="nofollow">http://dakrauth.com/blog/entry/python-and-django-setup-mac-os-x-leopard/</a></p>
<br /><b>#3</b><br /><p>I had the same problem on OSX 10.6.6. But just a simple <code>easy_install mysql-python</code> on terminal did not solve it as another hiccup followed:</p>

<p><code>error: command 'gcc-4.2' failed with exit status 1</code>. </p>

<p>Apparently, this issue arises after upgrading from XCode3 (which is natively shipped with OSX 10.6) to XCode4. This newer ver removes support for building ppc arch. If its the same case, try doing as follows before <code>easy_install mysql-python</code></p>

<pre><code>sudo bash
export ARCHFLAGS='-arch i386 -arch x86_64'
rm -r build
python setup.py build
python setup.py install
</code></pre>

<p>Many thanks to Ned Deily for this solution. <a href="http://stackoverflow.com/questions/5671480/trouble-setting-up-mysqldb-module">Check here</a></p>
<br /><b>#4</b><br /><p>Back to the original problem. Your on a Mac (not bloody Ubuntu!), and seemingly can install Python MySQLdb but get a sock error.
It seems Python / MySQLdb insists on using /tmp/mysql.sock no matter what you do, when in fact your mysql.sock file probably lives elsewhere (eg. /var/mysql/mysql.sock)</p>

<p>In your settings.py file, point HOST to the actual MySQL sock file you're using.</p>

<p>Another option is to simply make a link:</p>

<pre><code>ln -s /var/mysql/mysql.sock /tmp/mysql.sock
</code></pre>

<p>Not that nice, bit of a workaround, but seems to do the job. Note, you'll lose this when you logoff, so adjusting your settings.py file is a better option.</p>

<p>Ideally, MySQLdb could have its sock file adjusted from /tmp/mysql.sock, but I can't find a way to do that.</p>
<br /><b>#5</b><br /><p>Adding to other answers, the following helped me finish the installation mysql-python:</p>

<p><a href="http://stackoverflow.com/questions/1511661/virtualenv-mysql-python-pip-anyone-know-how">virtualenv, mysql-python, pip: anyone know how?</a></p>

<p>On Ubuntu...</p>

<pre><code>apt-get install libmysqlclient-dev
apt-get install python-dev
pip install mysql-python
</code></pre>

<p>Don't forget to add 'sudo' to the begging of commands if you don't have the proper permissions.</p>
<br />