<h3>Question ( ID-7799610 ) : </h3><h2>exceptions + signaling end-of-iterator : why is it bad in Java and normal in Python ? </h2><p>I 'm really confused : The standard approach in Java is to throw exceptions only in " abnormal " conditions and not to use them to signal end-of-iterator . </p>
<p>examples : Effective Java , item 57 ( " Use exceptions only for exceptional conditions " ) and JavaSpecialists newsletter 162 : </p>
<blockquote>Flow control We should never cause an exception that is otherwise preventable. I have seen code where instead of checking bounds , it is assumed that the data will be correct and then RuntimeExceptions are caught : Here is an example of bad code ( please do n't code like this ) : public class Antipattern1 { public static void main ( String [ ] <span style="background-color:yellow;">args</span> ) { try { int i = 0 ; while ( true ) { System.out.println ( <span style="background-color:yellow;">args</span> [ i + + ] ) ; } } catch ( ArrayIndexOutOfBoundsException e ) { // we are done } } } </blockquote>
<p>whereas it is standard to use this idiom in Python , e.g. StopIteration : </p>
<blockquote></blockquote>
<p>Why is it bad for Java but good for Python ? </p>
<br /><h3>Answers ( Total-6 ) : </h3><b># 0 </b><br /><p>Python and Java have vastly different approaches to exceptions. In Python , exceptions are normal. Look up EAFP ( Easier to ask for forgiveness than permission ) in the Python glossary. Also check what Wikipedia has to say . </p>
<p></p>
<p>If the code is more readable with a non-local exit , in Python you use an exception. You do n't write checks , you just deal with failures if things do n't work out. There 's absolutely nothing shameful about it , in fact it 's encouraged. Unlike in Java . </p>
<hr />
<p>Now for a specific case of StopIteration : Consider <span style="background-color:yellow;">generator</span> functions . </p>
<pre><code>def generator():
    yield 1
    print 'Side effect'
    yield 2
</code></pre>
<p>To support some kind of has_next ( ) method , the <span style="background-color:yellow;">generator</span> would have to check for the next value , triggering the print before the 2 is asked for. The value ( or exception raised ) would have to be remembered in the iterator. If has_next was called twice , only the first one would trigger the side effect. Or the next value could always be precomputed , even if it 's not needed . </p>
<p></p>
<p>Of course Java does n't have resumable <span style="background-color:yellow;">generators</span> , so it 's hard to compare here. But it 's some anecdotal evidence that StopIteration generalizes better than hasNext ( ) . </p>
<br /><b># 1 </b><br /><p>There is nothing that stops you from using exceptions like that in java , it just looks ugly , at least to a java developer . </p>
<p>The main reason is that stacktraces from exceptions are expensive , and possibly also that java developers might be slightly more concerned about spending computing resources than Python developers . </p>
<p>Java is also a rather " clean " language - some would say fundamentalistic , which is one of the reasons it 's a nice language. ( * see comment ) </p>
<p>Anyway. Fundamentalists ( and some normal people ) thinks that using exceptions for normal flow just is n't The Right Way... : - ) </p>
<p>But besides that , recent jvm 's detects that you are generating a lot of stacktraces for the same spot of code , and will actually throw exceptions without them " after a while " to speed up things . </p>
<br /><b># 2 </b><br /><p>Java sometimes does it , too : " All implementations of DataInput methods use EOFException instead of return values. " In this case there 's no way to use the usual sentinel value , -1 . </p>
<br /><b># 3 </b><br /><p>The reason its not recommended is because in java , exception handling is generally expensive to process and recover from. When an exception is thrown , it causes a the jvm to go backtrack what is was doing in order to provide a stack trace which is never a good thing for performance. In short , it 's language misuse - there will usually be a cleaner , more efficient way of handling logic. Consider the following code : </p>
<pre><code>try {

    int x = service.getValue();

    if(x > 5)
        throw new NumberTooBigException("Too Big");
    else
        throw new NumberTooSmallException("Too Small");

} catch (NumberTooBigException e) {

    System.out.println("i think it's too big...");

} catch (NumberTooSmallException e) {

    System.out.println("i think it's too small...");

}
</code></pre>
<p>A better approach is to use just use java 's intended control logic : </p>
<pre><code>if(x > 5)
    System.out.println("i think it's too big...");
else
    System.out.println("i think it's too small...");
</code></pre>
<p>As you can see from comparing these two snippets , exception handling is kind of ridiculous - overkill for what the sample intends to do. A better approach for the example you posted would be something like this : </p>
<pre><code>String[] args = {"one", "two", "three"};
for(String arg : args)
    System.out.println(args);
}
</code></pre>
<p>Exceptions are better used for when things really go wrong , like IOException ( " no space left on device " ) , ClassNotFoundException ( " ca n't find your code to run " ) or NoRouteToHostException ( " Ca n't connect to host " ) . </p>
<br /><b># 4 </b><br /><p>StopIteration exists in Python for simple iteration over any sequence . </p>
<p>Using an exception to implement this was a design choice , and it really is n't that inconsistent with Java 's exception mentality. An iterator 's next ( ) method being called when there are no more elements is an exceptional condition , and catching that exception behind the scenes in a for loop is a pretty simple way to implement " take items until there are n't any left " . </p>
<br /><b># 5 </b><br /><p>There is no right or wrong answer to this. Exception handling is a neutral control flow construct , and the best use of it depends on context and style . </p>
<p>In this case , both Java and Python do the same thing , for the same reasons : java.util.Iterator 's next ( ) uses NoSuchElementException to signal end-of-iterator. This is simply good style , in both languages : the alternative of using a special sentinel return value is is much worse , for various reasons . </p>
<p>As a rule of thumb , you should consider the use of exceptions whenever you write a function that wants to signal more than one kind of control flow return . This includes abnormal error conditions , but good use of exception signalling is certainly not limited to that . </p>
<br />